# Plataformas de financiamiento para el proyecto
# Descomenta y configura las que apliquen

# github: [tu-usuario]
# patreon: tu-usuario
# open_collective: bc-fastapi
# ko_fi: tu-usuario
# tidelift: npm/paquete
# community_bridge: proyecto
# liberapay: tu-usuario
# issuehunt: tu-usuario
# otechie: tu-usuario
# lfx_crowdfunding: proyecto
# custom: ['https://tu-link.com']
